definitions:
  Response:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
      type:
        type: string
    required:
    - message
    - type
    type: object
info:
  title: Swagger FH_assistant
  version: 1.0.0
paths:
  /v1/connect:
    post: {}
  /v1/hospitals:
    get:
      description: Recuperation de la liste des hopitaux
      responses:
        '200':
          description: Recuperation de la liste des hopitaux
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Erreur de token
          schema:
            $ref: '#/definitions/Response'
    post:
      description: Creation d'un nouvel hopital
      responses:
        '200':
          description: Recuperation de la liste des hopitaux
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: Erreur d'analyse du body
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Erreur de token
          schema:
            $ref: '#/definitions/Response'
        '409':
          description: La ressource existe deja
          schema:
            $ref: '#/definitions/Response'
  /v1/salles:
    get:
      description: Recuperation de la liste des salles
      responses:
        '200':
          description: Recuperation de la liste des salles
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Erreur de token
          schema:
            $ref: '#/definitions/Response'
swagger: '2.0'
